name: ledger_view
description: A modern Flutter app to view customer ledger data from Google Sheets

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  csv: ^5.1.1
  shared_preferences: ^2.3.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
